import React, { useState } from 'react';
import { Link } from 'react-router-dom';

const categories = ['Cars & Coffee', 'JDM', 'German', 'Supercars / Hyper', 'Track / Trackday', 'Classic & Vintage', 'Rally', 'Drift', 'Charity'];
const Field = ({ label, required, children }) => <label className="form-field"><span>{label} {required ? '*' : ''}</span>{children}</label>;

export default function SubmitMeet() {
  const [familyFriendly, setFamilyFriendly] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const submit = event => { event.preventDefault(); setSubmitted(true); };
  return <main className="submit-page"><header className="submit-header"><Link to="/">← BACK</Link><h1>SUBMIT A MEET</h1></header><form className="submit-form" onSubmit={submit}><p className="eyebrow">ORGANISER SUBMISSION · REQUIRES ADMIN APPROVAL</p><p className="submit-intro">Got a meet you want on Crystal Meets? Fill in the details below. An admin will review your submission and — if approved — it&apos;ll appear on the map and list. We may email you if we need anything clarified.</p><Field label="MEET NAME" required><input required placeholder="e.g. Dublin Sunday JDM Meet" /></Field><Field label="DESCRIPTION" required><textarea required placeholder="What kind of meet is this? Who is it for?" /></Field><div className="form-grid"><Field label="DATE & TIME" required><input type="datetime-local" required /></Field><Field label="CATEGORY" required><select defaultValue="Cars & Coffee">{categories.map(category => <option key={category}>{category}</option>)}</select></Field></div><div className="form-grid"><Field label="LOCATION NAME" required><input required placeholder="e.g. Mondello Park" /></Field><Field label="ADDRESS" required><input required placeholder="Full address including county" /></Field></div><div className="form-grid"><Field label="LATITUDE" required><input type="number" step="any" required placeholder="53.3475" /></Field><Field label="LONGITUDE" required><input type="number" step="any" required placeholder="-6.2312" /></Field></div><Field label="IMAGE URL"><input type="url" placeholder="https://... (car photo helps approval)" /></Field><div className="form-grid"><Field label="ORGANISER"><input placeholder="Club or organiser name" /></Field><Field label="ENTRY PRICE"><input placeholder="Free" /></Field></div><label className="family-toggle"><button type="button" className={familyFriendly ? 'switch on' : 'switch'} onClick={() => setFamilyFriendly(!familyFriendly)}><b /></button>Family Friendly</label><section className="contact-section"><p className="eyebrow">YOUR DETAILS (FOR ADMIN FOLLOW-UP)</p><div className="form-grid"><Field label="YOUR EMAIL" required><input type="email" required placeholder="you@example.com" /></Field><Field label="YOUR NAME"><input /></Field></div><Field label="NOTES FOR THE ADMIN (OPTIONAL)"><textarea placeholder="Anything the admin should know when reviewing?" /></Field></section><footer className="submit-footer"><small>Submissions are moderated before appearing on the map.</small><button type="submit">⌁ SUBMIT FOR REVIEW</button></footer>{submitted && <p className="submit-success">Saved locally. Add your email settings later to forward this to your inbox.</p>}</form></main>;
}
